### ISSUE TITLE
Report objects who sharing a material to avoid lightmap problem

### ISSUE THREAD

**Issue by cstfan** [Vinc3r/ReTiCo#54]
If 2 objects share the same material 

![image](https://user-images.githubusercontent.com/33685211/72805166-8b48a480-3c52-11ea-9489-40b739c883c2.png)

there will be a problem when we apply the lightmaps.
With this report, we can check to the scene is ready for LM.

Maybe the same button for this report and this #52.

To avoid this, you can of course type Make Single User in Search and choose Material
![image](https://user-images.githubusercontent.com/33685211/72806157-dd8ac500-3c54-11ea-9438-af20d94a7e35.png)

**Comment by Vinc3r** [comment]
'could be nice to have choice between change objects selection or just made a report

![image](https://user-images.githubusercontent.com/3873421/72808234-6efc3600-3c59-11ea-9b99-e3eae09a7be0.png)

(these buttons could be use in other parts of the addon)

**Comment by cstfan** [comment]
To also have the selection would be top
