### ISSUE TITLE
Random error message by clicking on the Instances button with "To clipboard" activated

### ISSUE THREAD

**Issue by cstfan** [Vinc3r/ReTiCo#64]
By clicking on the Instances button with "To clipboard" activated, I sometimes get this error message:

![Erreur_message_1](https://user-images.githubusercontent.com/33685211/73064236-0d2e0d00-3ea1-11ea-85e5-420e1364f127.jpg)

[List of selected objects.txt](https://github.com/Vinc3r/ReTiCo/files/4107990/List.of.selected.objects.txt) when I got the message.

**Comment by Vinc3r** [comment]
I hope its fixed on https://github.com/Vinc3r/ReTiCo/commit/33f4a01a40d193f16da1c3a332e726ccac59736d

**Comment by cstfan** [comment]
Apparently, it's OK, great.

**Comment by Vinc3r** [comment]
nice !
