### ISSUE TITLE
Ability to export or not the Ambient Occlusion

### ISSUE THREAD

**Issue by cstfan** [Vinc3r/ReTiCo#71]
Changing the property name of the Group Node "glTF Settings" to "glTF Settings OFF" to disable the export of the Ambient Occlusion
![image](https://user-images.githubusercontent.com/33685211/79916986-f8bec980-8429-11ea-98c5-e73393256114.png)

**Comment by Vinc3r** [comment]
Instead of change node name, I will link/unlink the node group.

**Comment by cstfan** [comment]
Link/Unlink is the best method because if we mute of node gtTF Setting, the Occlusion map is still exported.

If we can also manage the case where we don't have an ORM map it would be great.
![image](https://user-images.githubusercontent.com/33685211/93778398-2781db80-fc26-11ea-8866-4650d47f2db7.png)

**Comment by Vinc3r** [comment]
before closing: check if "unmute all" relink the SEPRGB node
