### ISSUE TITLE
Add ReTiCo to title for better visibility in pin mode

### ISSUE THREAD

**Issue by cstfan** [Vinc3r/ReTiCo#78]
For better visibility in pin mode add ReTiCo to title

![image](https://user-images.githubusercontent.com/33685211/106728328-9deb0d00-660c-11eb-954d-f8198ce68cbd.png)

**Comment by Vinc3r** [comment]
I have to check if I can access tu [use_pin](https://docs.blender.org/api/current/bpy.types.Panel.html?highlight=use_pin#bpy.types.Panel.use_pin) value. If not, I prefer not to use too long Panel titles.

**Comment by cstfan** [comment]
I just tried it to see what it looks like, in fact it's a very bad idea, the visibility is much less good.
Moreover, if you think about it, there is no risk of confusing it with other titles. Don't touch anything, it's great like that.

![image](https://user-images.githubusercontent.com/33685211/109360977-63316900-7888-11eb-8818-63f6405058c6.png)
