### ISSUE TITLE
Exclude from the BackFace function, objects that have a specific suffix 

### ISSUE THREAD

**Issue by cstfan** [Vinc3r/ReTiCo#79]
When our objects are petals or leaves we do not want to apply a backface culling by mistake. For this reason, it would be interesting to be able to exclude objects with a specific suffix from the BackFace function.
Example: Flower_01_leaves_reticobfc

**Comment by Vinc3r** [comment]
mmh I don't think it's the right way to do. You better have to put your objects in a dedicated collection, and just not select them when clicking on BackFace button, isn't it?

**Comment by cstfan** [comment]
I've tried to make better use of the collections to do that and indeed it's working pretty well, thanks.
